theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Hugo Villanúa Vega
description: Engineering, management and robots
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: G-1CNCCNSZTX

show_hyperlinks: true
resume: /assets/pdf/HVV_resume.pdf

github:
  is_user_page: false